knpu_oauth2_client:
    clients:
        discord:
            type: discord
            client_id: '%env(OAUTH_DISCORD_CLIENT_ID)%'
            client_secret: '%env(OAUTH_DISCORD_CLIENT_SECRET)%'
            redirect_route: connect_discord_check
        blizzard:
            type: generic
            provider_class: League\OAuth2\Client\Provider\GenericProvider
            client_id: '%env(OAUTH_BNET_CLIENT_ID)%'
            client_secret: '%env(OAUTH_BNET_CLIENT_SECRET)%'
            redirect_route: connect_blizzard_check
            provider_options:
                urlAuthorize: 'https://%env(BLIZZARD_REGION)%.battle.net/oauth/authorize'
                urlAccessToken: 'https://%env(BLIZZARD_REGION)%.battle.net/oauth/token'
                urlResourceOwnerDetails: 'https://%env(BLIZZARD_REGION)%.api.blizzard.com/oauth/userinfo'
