knpu_oauth2_client:
    clients:
        discord:
            type: discord
            client_id: '%env(OAUTH_DISCORD_CLIENT_ID)%'
            client_secret: '%env(OAUTH_DISCORD_CLIENT_SECRET)%'
            redirect_route: '%env(OAUTH_DISCORD_REDIRECT)%'
            redirect_params: {}
            use_state: true
