nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(string:CORS_ALLOW_ORIGIN)%']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        expose_headers: []
        max_age: 3600
    paths:
        '^/connect/':
            allow_origin: ['%env(string:CORS_ALLOW_ORIGIN)%']
            allow_credentials: true
        '^/api/':
            allow_origin: ['%env(string:CORS_ALLOW_ORIGIN)%']
            allow_credentials: true
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
