nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['%env(FRONT_ORIGIN)%']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        expose_headers: ['Set-Cookie']
        max_age: 3600
    paths:
        '^/connect/':
            allow_origin: ['%env(FRONT_ORIGIN)%']
            allow_credentials: true
        '^/api/':
            allow_origin: ['%env(FRONT_ORIGIN)%']
            allow_credentials: true
        '^/debug/':
            allow_origin: ['%env(FRONT_ORIGIN)%']
            allow_credentials: true
